### PR TITLE
allow to set an environment variable to enforce an identity to use

### PR DESCRIPTION
**Pull request by trefzer**

### CODE REVIEW

**Comment by maddes-b** [comment]
Hello trefzer,

I had a similar feature in my previous fork, but it always turned out that the configuration was not complete or not implemented correctly (directory, arguments).
Only for ssh-add I needed to choose an identity, that's why implemented the virtual parameters -i/-I for ssh-add executables.

What are your use cases for this feature?

Kind regards
Maddes

**Comment by trefzer** [comment]
Hi
I have some scripts, that connect to several hosts to do work (eg updates etc). With the use of an envrionment variable I have a simple solution to choose an appropriate key (eg. one that does not need touching all the time).
It also makes testing simpler, since I can use a 'test' environment without changing the used agent upon rules.

The ultimate feature I like to have is the possibility to choose the agent to use on command line like host.env1 connects me to host using agent env1 (of course I would also like to use host.env2 for connecting to the same host but using agent env2).
But this would require a rewrite of the hostname to connect to, which is not simple, so I came up with this much simpler solution.

**Comment by maddes-b** [comment]
You can determine identity on the given arguments for the "ssh" executable. If you want to check  for `<user>@<host>` then the normal `MATCH_ARGV` functionality will work just fine for you.
I use `MATCH_ARGV` for multiple GitHub accounts, see https://superuser.com/questions/232373/how-to-tell-git-which-private-key-to-use/1616186#1616186, where I even need a regex for the whole argument line and not just a check on a single argument.

For testing the environment variable can be quite convenient, still a good `.ssh-ident` configuration is the best way to go.
For more complex tests I just symlink different `.ssh-ident` files.

Right now I'm not convinced to reimplement this eenv var, because users will use this workaround instead of creating a working configuration.

**Comment by maddes-b** [comment]
Using an environment variable is already implemented via `SSH_IDENT_ID`, see https://github.com/ssh-ident/ssh-ident1/blob/d0677413090de71cf9e0c53f1a79edabca9beaab/ssh-ident#L1466 and readme.
Your functionality is to define which env var to use, adding another abstraction layer to it.

The change should be applied around line 1466 and would also need some guarding code.

Please adapt to `SSH_IDENT_ID`.

**Pull request closed without merging**
